# Generated by Django 2.2.18 on 2021-03-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_accountproduct_given_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountproduct',
            name='given_bid',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
