# Generated by Django 2.2.18 on 2021-03-01 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_remove_auction_products'),
        ('products', '0005_auto_20210301_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctioned_product', to='auction.Auction'),
        ),
        migrations.DeleteModel(
            name='AuctionedProduct',
        ),
    ]
