# Generated by Django 2.2.18 on 2021-03-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210301_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
