# Generated by Django 2.2.18 on 2021-03-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
