# Generated by Django 2.2.18 on 2021-03-02 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_product_is_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='winning_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
