# Generated by Django 2.2.18 on 2021-03-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_winning_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highest_bid',
            field=models.IntegerField(default=0),
        ),
    ]
