# Generated by Django 2.2.18 on 2021-02-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_bidder',
            field=models.BooleanField(default=True),
        ),
    ]
