# Generated by Django 2.2.18 on 2021-02-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_is_bidder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bidder',
        ),
    ]
