# Generated by Django 2.2.18 on 2021-02-25 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0002_auto_20210225_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='members',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
