# Generated by Django 2.2.18 on 2021-02-25 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
