# Generated by Django 2.2.18 on 2021-02-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auctionedproduct'),
        ('auction', '0006_auction_particating_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='products',
            field=models.ManyToManyField(through='products.AuctionedProduct', to='products.Product'),
        ),
    ]
