# Generated by Django 2.2.18 on 2021-03-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auction_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionparticipant',
            name='given_bid',
            field=models.IntegerField(default=0),
        ),
    ]
