# Generated by Django 2.2.18 on 2021-03-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_remove_auctionparticipant_given_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='products',
        ),
    ]
