# Generated by Django 2.2.18 on 2021-03-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_remove_auction_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_type',
        ),
    ]
