# Generated by Django 2.2.18 on 2021-03-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_remove_auction_lowest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
